backend:
  name: git-gateway
  repo: zanonnicola/lopenlab
  branch: dev

media_folder: static/assets

publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - label: "Pages"
    name: "pages"
    files:
      - file: "src/pages/en/workshop/index.md"
        label: "Workshop [EN]"
        name: "en-workshop"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page-workshop"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/workshop/index.md"
        label: "Atelier [FR]"
        name: "fr-workshop"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page-workshop"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/contact/index.md"
        label: "Contact Page [FR]"
        name: "fr-contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page-contact"}
          - {label: Title, name: title, widget: string}
          - {label: Meta Description, name: metaDescription, widget: string}
          - {label: Sub Title, name: subTitle, widget: string}
          - {label: Contact Box Title, name: contactBoxTitle, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/en/contact-us/index.md"
        label: "Contact Page [EN]"
        name: "en-contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page-contact"}
          - {label: Title, name: title, widget: string}
          - {label: Meta Description, name: metaDescription, widget: string}
          - {label: Sub Title, name: subTitle, widget: string}
          - {label: Contact Box Title, name: contactBoxTitle, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/en/holidays/index.md"
        label: "Holidays Page [EN]"
        name: "en-holidays"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page-holiday"}
          - {label: Title, name: title, widget: string}
          - {label: Meta Description, name: metaDescription, widget: string}
          - {label: Sub Title, name: subTitle, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/holidays/index.md"
        label: "Vacances Page [FR]"
        name: "en-holidays"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page-holiday"}
          - {label: Title, name: title, widget: string}
          - {label: Meta Description, name: metaDescription, widget: string}
          - {label: Sub Title, name: subTitle, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/team/index.md"
        label: "L’équipe Page [FR]"
        name: "fr-team"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page-team"}
          - {label: Title, name: title, widget: string}
          - {label: Meta Description, name: metaDescription, widget: string}
          - {label: Sub Title, name: subTitle, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/en/team/index.md"
        label: "Team Page [EN]"
        name: "en-team"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page-team"}
          - {label: Title, name: title, widget: string}
          - {label: Meta Description, name: metaDescription, widget: string}
          - {label: Sub Title, name: subTitle, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/pedagogy/index.md"
        label: "Pedagogy Page"
        name: "fr-pedagogy"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "pedagogy-page"}
          - {label: Title, name: title, widget: string}
          - {label: Meta Description, name: metaDescription, widget: string}
          - {label: Sub Title, name: subTitle, widget: string}
          - {label: Contact Box Title, name: contactBoxTitle, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}